### ISSUE TITLE
Remove dependency from scss

### ISSUE THREAD

**Issue by bogas04** [HriBB/react-mdl-extra#1]
Bringing the issue from [react-mdl-selectfield](https://github.com/HriBB/react-mdl-selectfield).

**Comment by HriBB** [comment]
Hey @bogas04, do you want to make a PR? It's on my TODO list, but I don't have much time ATM.

**Comment by bogas04** [comment]
Hey @HriBB . Sorry bit busy this week. I'll try this weekend maybe.

**Comment by HriBB** [comment]
Done! https://github.com/HriBB/react-mdl-extra/releases/tag/v1.4.3

**Comment by bogas04** [comment]
Thank you so much!
