### ISSUE TITLE
Cannot read property 'offsetTop' of undefined at OptionList.js:71

### ISSUE THREAD

**Issue by lina128** [HriBB/react-mdl-extra#15]
I got this error when using MultiSelectField with a long list.

I tracked line 68-71: _list$getElementsByCl was an empty array, _list$getElementsByCl2  was an empty array too, and selected was undefined.

When the above lines were executed, there was no 'mdl-option--selected' classes. The code was trigged when I clicked the input field, before I even clicked any option.

The component behaved as expected though. So what does this part do?

**Comment by HriBB** [comment]
@Lina128 thanks for the bug report. I am on vacation in Turkey ATM, will check this out when I come back.

**Comment by HriBB** [comment]
I think it might be a babel transpiler problem. I am doing some es6 destructuring and babel inserts some of it's magic. Which browser are you using?

**Comment by marcelpanse** [comment]
Hi @HriBB - I'm having the same issue with the MultiSelectField
Stacktrace: https://cl.ly/051x3O06281Q
Using Chrome 64.0 on OSX 10.13.3

Any idea how we can get rid of the console error log? The component works as expected though.

**Comment by HriBB** [comment]
@marcelpanse I'm not sure, would need to debug it.

I am not using or supporting this library anymore. But you can make a PR if you wish. Having said that, I might find some time next week, but I cannot promise anything, because I have a lot of work.

If you can make a reproducible example, it would help me a lot. You can just write down steps to reproduce it.

**Comment by marcelpanse** [comment]
Hey @HriBB, thanks for checking it out, but if you are not maintaining this anymore then don't bother, I already forked it to make a couple of changes.

**Comment by HriBB** [comment]
Yeah, I've started using https://material-ui-next.com/.

Just make a PR and I can merge it. I can also give you full access, if you wish to maintain this library.

**Comment by marcelpanse** [comment]
We need to upgrade ourselves as well.. looking at https://kradio3.github.io/react-mdc-web/components/menu/ which is wrapper on the new MDC
