### ISSUE TITLE
Big library size

### ISSUE THREAD

**Issue by koutsenko** [HriBB/react-mdl-extra#7]
When i did npm i --save react-mdl-extra, I see a 2Mb /dist folder ...
No sense it is minified or not - it consumes 1Mb traffic. It's just for one GUI control!
Can you rebuild it without React or add appropriate package.json section? 

Thanks.

**Comment by HriBB** [comment]
Thanks for the heads up @koutsenko. I don't use the UMD build so I did not even notice. I excluded react from the build and now it's some 165kb. Any ideas on how to bring it down even more?

**Comment by koutsenko** [comment]
Maybe your webpack configuration file have no uglify plugin enabled?
I don't checkout new version yet, but previous webpack.config.js is missing something like that
```
 plugins: [
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
        drop_console: true,
        unsafe: true
      }
    })
  ],
```
p.s. of course, it must be enabled only for NODE_ENV=production config..
In my own project i created two different config files due to many differences in settings and plugin set

**Comment by HriBB** [comment]
@koutsenko sorry for the late reply. I am using uglify plugin for minified universal build, see [here](https://github.com/HriBB/react-mdl-extra/blob/master/webpack.config.js#L56-L72), but the library size is still somewhat big.

`react-mdl-extra.min.css` = 11,3 kB
`react-mdl-extra.min.js` = 168,2 kB

I think users can benefit by using es6 modules and tree-shaking with webpack 2. Not really 100% sure if this package is ready for that. If anyone is willing to check it out and making it work with tree-shaking, that would be awesome.

I'm closing this issue for now, @koutsenko please feel free to reopen if you think that there's still a problem with this library.
